on:
  workflow_call:
    secrets:
      LEETCODE_USER:
        required: true
      LEETCODE_TOKEN:
        required: true


jobs:
  lint:
    name: "Lint Sources"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install
        shell: bash
      - run: yarn flow-typed-install
        shell: bash
      - run: yarn flow
        shell: bash
      - run: yarn lint
        shell: bash
  test:
    name: "Test Project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install
        shell: bash
      - run: |
          touch account.txt
          echo "${{ secrets.LEETCODE_USER }}" >> account.txt
          echo "${{ secrets.LEETCODE_TOKEN }}" >> account.txt
        shell: bash
      - run: yarn leetcode user -g < account.txt
        shell: bash
      - run: yarn leetcode session
        shell: bash
      - run: NODE_ENV=test yarn c8 yarn test
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_${{ github.sha }}
          path: |
            ./coverage
          if-no-files-found: error
          retention-days: 1
  coverage:
    name: "Report Coverage"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: coverage_${{ github.sha }}
      - uses: codecov/codecov-action@v3
